[PLAT-935] - Add generalized github actions for JIRA integration
ratehub/jira-actions pull request #1
Opened 2021-01-25 14:42 UTC by rach1416

Three generalized actions has been added as part of this PR - Uses node.js wrapper for JIRA API
1. check_release_version: Checks if the required release version already exists in the project
2. create_release_version: Creates a release version if doesn't already exist in the project
3. update_issue_version: Assigns the fixVersion for the JIRA ticket which is retrieved from the commit message.

2021-01-28 23:11 UTC, jkirkham-ratehub requested changes

2021-01-28 23:11 UTC, jkirkham-ratehub commented on check_version_status/index.js
> +    if (release == 'current'){
So, I'm unfamiliar with the framework for Actions, but it looks like there is no validation on the input.  It is marked as `required` here check_version_status/action.yml but nothing else.  Since JS is a dynamic language you need to add your own constraints.  You handle 2 cases `current` and `next` but don't handle the case for other values including empty strings, undefined, typos, or completely different values.  Outside the 2 handled options what happens with invalid input?
Below you check if the returned value matches a project version and then whether this "find" operation result is defined but I don't think it provides any feedback on the source of the problem (the inputs).  The project lookup may fail (again that too may be due to invalid input or perhaps a network or server error) and so the errors are all compounded with no context.
You should at least log the error condition here (and where ever possible)  so it will be easier to track down the cause(s).  It is always better to fail early (immediately) than to pass an error on (in my opinion this is one of the big faults with the way exception handling is often used.)
This no doubt applies to all 3 of the Actions.

2021-01-28 23:11 UTC, jkirkham-ratehub commented on check_version_status/index.js
> +        const statusCode = '200';
Why use status Code 200 or 400 here?  These are commonly for web-request statuses but the web api call happened earlier `jira.getVersions` so you should check the status there and return it if it is not valid.

2021-01-28 23:11 UTC, jkirkham-ratehub commented on check_version_status/index.js
> +const jira = new JiraApi({
The trouble with declaring the `jira` client const here is that there is no check to see if it succeeded.  Does it need to be global?

2021-01-28 23:37 UTC, rach1416 commented on check_version_status/index.js
> +    if (release == 'current'){
will update the actions to handle other cases and exceptions.

2021-02-01 13:34 UTC, rach1416 commented on check_version_status/index.js
> +    if (release == 'current'){
Will be resolved in another PR.

2021-02-01 13:34 UTC, rach1416 commented on check_version_status/index.js
> +        const statusCode = '200';
Will be updating them in another PR.

2021-02-01 13:34 UTC, rach1416 commented on check_version_status/index.js
> +const jira = new JiraApi({
Will be updating them in another PR.

2021-02-01 13:38 UTC, rach1416 commented
Merging this PR, as the change requests are non-blocking and will be resolved in a new PR.

2021-02-01 13:39 UTC, merged